name: Update Repository Description

on:
  push:
    branches: [main]
    paths: ["README.md"]

jobs:
  update-description:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Extract description from README
        id: extract
        run: |
          # Extract the description (first paragraph after title)
          description=$(sed -n '/^# Verbatim AI/,/^## /{ /^# Verbatim AI/d; /^## /d; p; }' README.md | head -1 | sed 's/^A //')
          echo "description=$description" >> $GITHUB_OUTPUT

      - name: Update repository description
        uses: actions/github-script@v7
        with:
          script: |
            const description = '${{ steps.extract.outputs.description }}';
            if (description && description.trim()) {
              await github.rest.repos.update({
                owner: context.repo.owner,
                repo: context.repo.repo,
                description: description.trim()
              });
            }
